// Generated by 'unplugin-auto-import'
export {}
declare global {
  const breakpoints: typeof import('./src/mixins/detectMobile')['breakpoints']
  const isMobile: typeof import('./src/mixins/detectMobile')['isMobile']
  const lg: typeof import('./src/mixins/detectMobile')['lg']
  const md: typeof import('./src/mixins/detectMobile')['md']
  const sm: typeof import('./src/mixins/detectMobile')['sm']
  const xl: typeof import('./src/mixins/detectMobile')['xl']
  const xxl: typeof import('./src/mixins/detectMobile')['xxl']
  const xxxl: typeof import('./src/mixins/detectMobile')['xxxl']
}
// for vue template auto import
declare module 'vue' {
  interface ComponentCustomProperties {
    breakpoints: typeof import('./src/mixins/detectMobile')['breakpoints']
    isMobile: typeof import('./src/mixins/detectMobile')['isMobile']
    lg: typeof import('./src/mixins/detectMobile')['lg']
    md: typeof import('./src/mixins/detectMobile')['md']
    sm: typeof import('./src/mixins/detectMobile')['sm']
    xl: typeof import('./src/mixins/detectMobile')['xl']
    xxl: typeof import('./src/mixins/detectMobile')['xxl']
    xxxl: typeof import('./src/mixins/detectMobile')['xxxl']
  }
}
